# Generated by Django 4.2.6 on 2024-06-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="jobs",
            fields=[
                ("job_id", models.IntegerField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(max_length=10)),
                ("job_category", models.CharField(max_length=10)),
                ("job_description", models.CharField(max_length=200)),
                ("job_requirement", models.CharField(max_length=200)),
                ("job_salary", models.IntegerField()),
                ("job_icon", models.ImageField(upload_to="")),
                ("job_status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("phone", models.IntegerField(unique=True)),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=10)),
                ("user_type", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="payment",
            fields=[
                ("payment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("payment_status", models.CharField(max_length=20)),
                ("amount", models.IntegerField()),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.jobs"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jobs",
            name="job_provider_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
        ),
    ]
